# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d25bda0254d4197a350fe26430b234c15052528f43f069349a4124c3876c14e71859ade8f7397ce5ff44230f8ebd5626f189194dd9b32987dc419fe596686bb

test:
  secret_key_base: b386ec0e7cba9f2c825b8ed05cbdae5ceda400729d0cdc493d1ba62376dc0fb0372a08874ab43d92b165679b0831f64e0234d54f1186d35414e70b2abf2a0f69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
